apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pihole
  name: pihole-ingress
spec:
  rules:
  - host: pihole.10.20.0.240.nip.io
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
              name: pihole-web
              port:
                number: 80

