apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "homebridge"
  name: "homebridge"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"

