apiVersion: v1
kind: PersistentVolume
metadata:
  name: "grafana"
  labels:
    type: "local"
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/grafana"

