apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prometheus"
  labels:
    type: "local"
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/prometheus"

